# select 옵션 제거, INPUT_SELECTION 제거
# rollback코드 태그삭제 부분 수정
name: Patch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_version_only:
    runs-on: ubuntu-latest
    steps:
      - name: checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 100
      - name: setup git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: save current HEAD (for rollback)
        run: echo "OLD_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: update version
        run: |
          CURRENT_VERSION=$(cat info/version.info)

          echo "CURRENT_VERSION: $CURRENT_VERSION"

          MAJOR=$(echo "${CURRENT_VERSION}" | cut -d '.' -f1)
          MINOR=$(echo "${CURRENT_VERSION}" | cut -d '.' -f2)
          PATCH=$(echo "${CURRENT_VERSION}" | cut -d '.' -f3)

          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"


          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo $NEW_VERSION > info/version.info
          echo "Updated Version to $NEW_VERSION"

          git add info/version.info
          git commit -m "Update Version to ${NEW_VERSION}"
          git push origin release

      - name: tag process
        run: |
          set -e  # terminate on error

          VERSION_TAG="v${{ env.NEW_VERSION }}"

          git tag "${VERSION_TAG}"
          git push origin "${VERSION_TAG}"

          git fetch --tags
          if git rev-parse --verify --quiet "QC"; then
            git tag -f QC
          else
            git tag QC
          fi
          git push -f origin QC

      - name: merge release into main
        run: |
          git fetch origin main
          git switch -c main origin/main

          if ! git merge --ff-only origin/release; then
            echo "FF merge failed, falling back to no-FF merge."
            git merge --no-ff -X theirs origin/release -m "ff merge failed. Release branch fixes are applied first"
          fi
          git push origin main
      - name: rollback if failure
        if: ${{ failure() }}
        run: |
          echo "An error occurred, rolling back changes..."
          git reset --hard "${{ env.OLD_HEAD }}"
          git push origin HEAD:release --force
          if [ -n "${{ env.NEW_VERSION }}" ]; then
            git tag -d "v${{ env.NEW_VERSION }}"
            git push origin :refs/tags/"v${{ env.NEW_VERSION }}"
          fi
